#include $(srctree)/drivers/misc/mediatek/Makefile.custom

#include $(srctree)/drivers/misc/mediatek/imgsensor/src/Makefile.custom
obj-y += ov20880pd1901v2mipiraw_Sensor.o
obj-y += ov20880pd1901v2mipiraw_otp.o
