
ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/include
ccflags-y += -I$(srctree)/drivers/misc/mediatek/base/power/$(MTK_PLATFORM)
#obj-$(CONFIG_BBK_ICNF7319)	+= fpsensor_tee.o
#fpsensor_tee-objs := fpsensor_spi_tee.o

obj-$(CONFIG_BBK_ICNF7312)	+= fpsensor_spi_tee.o