# Touchscreen Log switch
obj-y	+= bbk_drivers_info.o
obj-y	+= bbk_card_detect.o
obj-y	+= bbk_boards_version.o
#add by huaqin for simtray detect start
obj-$(CONFIG_BBK_SIMTRAY_STATUS_DETECT)	+= bbk_simtray_state_detect.o
#add by huaqin for simtray detect end