#include $(srctree)/drivers/misc/mediatek/Makefile.custom

#include $(srctree)/drivers/misc/mediatek/imgsensor/src/Makefile.custom
obj-y += ov20880pd1901v1mipiraw_Sensor.o
obj-y += ov20880pd1901v1mipiraw_otp.o
